site_name: David Pan's Notebook
site_url: https://david-pigeon.github.io/notebook/
repo_name: DaViD-Pigeon/notebook
repo_url: https://github.com/DaViD-Pigeon/notebook
site_description: A notebook for David Pan

theme:
  name: material
  language: zh
  logo: aniya.ico
  favicon: aniya.ico

  features:
    - content.code.annotate
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top

  font:
    text: LXGW WenKai Screen
    code: JetBrains Mono

  palette:     #切换昼夜模式的颜色，审美差就用默认，专业点就自定义
    - media: "(prefers-color-scheme: light)" 
      scheme: default  #配色方案：浅色模式
      toggle:
        icon: material/weather-sunny #图标，太阳
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"  
      scheme: slate  #配色方案：深色模式
      # primary: Brown  #原色，默认蓝，用于标题、侧边栏、文本链接和其他几个组件
      toggle:
        icon: material/weather-night  #图标，月亮
        name: Switch to light mode

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - meta
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols  #智能符号
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - https://gcore.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
  - stylesheets/flink.css
  - stylesheets/custom.css

extra_javascript:
  - js/baidu-tongji.js
  - https://gcore.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.js
  - js/katex.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/DaViD-Pigeon

nav:
  - Home:
    - index.md
    - 友链: link.md
  - Paper: 
    - Paper/index.md
    - TTS:
      - Intro: Paper/index_tts.md
      - Fastspeech: Paper/fastspeech.md
    - SVS:
      - Intro: Paper/index_svs.md
      - DiffSinger: Paper/diffsinger.md

    - Transformer:
      - Intro: Paper/index_tf.md
      - Paper/transformer.md

    - Jailbreak For LLM:
      - Intro: Paper/index_jail.md
      - GCG: Paper/GCG.md
      - AutoDAN: Paper/Autodan.md
